### ISSUE TITLE
Add README / long description to mozilla-aws-cli-mozilla pypi package

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-aws-cli#125]
See https://pypi.org/project/mozilla-aws-cli-mozilla/ - its fairly bare right now :)

Note: you might also just want to rename the project to `maws` so that people can `pip install maws` and get the `maws` CLI (easier)

Alternatively, maybe there should be a main package called `mozilla-aws-cli` with a configuration for Mozilla's specific use of it. Right now if one doesn't read the mana pages, its kind of confusing

**Comment by gene1wood** [comment]
Done in mozilla-iam/mozilla-aws-cli-mozilla#1 and released in [v1.0.0](https://pypi.org/project/mozilla-aws-cli-mozilla/1.0.0/)
