### ISSUE TITLE
mozilla-aws-cli package does not place a default config

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-aws-cli#126]
This is what you get when you install only the default package, `mozilla-aws-cli` from pip or from `setup.py`:

`Error: Invalid value for "-c" / "--config": Config files /etc/mozilla_aws_cli/config /home/kang/.maws/config not found`

It looks like `setup.py` should place a default `config` file in `/etc/mozilla_aws_cli/config` when calling `setup.py install`

**Comment by gene1wood** [comment]
So we don't create a default config because all the values in the config are required and have no defaults (they are values that we can't guess). For users installing `mozilla-aws-cli` we want to require that they create a config file before being able to use the tool.

**Comment by gdestuynder** [comment]
the users don't know where the system global file goes if its not present, and then you have to figure out what values would be in it.

if you ever installed a CLI program, and it didnt run, and you had to lookup the manual to find the configuration syntax - you know how very annoying that is :)

I forced this behavior in the Arch package (and intend to keep it that way)

**Comment by gene1wood** [comment]
Since we can't produce default config values (because there are no defaults), what would be a good fix for this?

Are you thinking that the command line tool, when it detects no config, should produce and write to disk an empty config file or a config file with no values but with comments in it?

**Comment by gdestuynder** [comment]
This is the fix i used for the package:

- I bundle https://aur.archlinux.org/cgit/aur.git/tree/config?h=python-mozilla-aws-cli-git
- I copy it in `/etc/mozilla_aws_cli/config`

When you run the CLI it will will complain, but you can now edit that file or cp it in your home dir and edit it, without having to find the right documentation.

It's also possible to automatically create a file on disk, but I think I prefer the method where its present in /etc (or `$sysconfigdir`). Up to you. Another alternative is to have it at least in `/usr/share/appname` (ie `$PREFIX/share/appname`).

**Comment by gdestuynder** [comment]
If that's easier: I'd basically bundle the same file as above (or similar, but commented out) and package it through `setup.py` so that it ends up in `$sysdir` (ie something like `$PREFIX/etc` that python tools figure out for you, so on macOS it'll correctly end up in `/usr/local/etc` for example), which I think is generally sufficient.

**Comment by gene1wood** [comment]
Would you be open to creating a default config with no values (just comments) in the user's `~/.maws` (or soon to be `~/.config/maws`) directory so as to avoid users having to install the package as root? The intent of the `/etc` config was for a system wide thing, probably deployed by an administrator or IT department or something.

Also, how important would you rank this? Is this a blocker for release to the rest of Mozilla?

**Comment by gdestuynder** [comment]
not a blocker, and, i think it makes sense for the setup.py to place the config in `/etc` because its for system style installs - but if its at least in `~/.config/maws` as a user I know I wouldn't mind too much because i'd look there next

Note `/etc/aws_...` should also probably be `/etc/maws/config` to match (just saw this)

**Comment by gene1wood** [comment]
@gdestuynder How do you feel [about this addition to the README](https://github.com/mozilla-iam/mozilla-aws-cli/pull/154/files#diff-04c6e90faac2675aa89e2176d2eec7d8) which explains the config files, the fields and the format? Would the example added to the README work for helping a user know how to create a config?

**Comment by gdestuynder** [comment]
definitely helps. if there's no default config, maybe the readme.md should be installed as a man page for `man maws`?

**Comment by gene1wood** [comment]
Some information no python packages and man pages : pypa/packaging-problems#72

**Comment by gene1wood** [comment]
I'll close this as the guidance about the config file is in the README but not yet in a man page. We could open an issue to add the creation of a man page when the package is installed ( pypa/packaging-problems#72 ). If someone would like that feel free to open an issue for a man page
