### ISSUE TITLE
Add CLI option to override the default local profile on disk

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-aws-cli#132]
such as
`maws -o awscli --override-default` so that `~/.aws/credentials` has a `[default]` entry for example

**Comment by april** [comment]
Is calling `aws` with `--profile default` sufficient for this?

**Comment by gdestuynder** [comment]
If I'm understanding you correctly: `aws --profile generated_name_here` is how it works right now, with `aws --profile default` it will fail if you have no default profile

ex:

`maws -o awscli` will create this in `~/.aws/credentials`:
```
[MAWS_Something]                                                                                                                                
  aws_access_key_id = xxx
  aws_secret_access_key = yyyy
...
```

so you then have to call `aws --profile MAWS_Something` or `export AWS_PROFILE=MAWS_Something`

with `maws -o awscli --override-default` the proposal would be to create the entry in  `~/.aws/credentials` such as this:

```
[default]
  aws_access_key_id = xxx
  aws_secret_access_key = yyyy
...
```

so that you can just call `aws` without setting any profile

**Comment by gdestuynder** [comment]
side note, if your question had a typo where `aws` should be `maws` then, yes `maws --profile default` is probably fine. I don't know if it would be confusing or not to others, but it wouldn't bother me.

**Comment by april** [comment]
Nope, I had meant `aws`. So calling `aws` without a profile name will set it on default?

So the idea is that `maws` would have a `--profile` option, and if that profile was `default` then it would call `aws` without using `--profile`, correct?

**Comment by gdestuynder** [comment]
yea, called `aws` without a `--profile` and without the env var `AWS_PROFILE` set will default to `default`

what i'm thinking is:
`maws --profile default -oawscli` will overwrite any `[default]` profile from `~/.aws/{config,credentials}`  instead of creating/override a profile with it's own profile name
