### ISSUE TITLE
Launching from command line requires role-picker to launch twice

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/mozilla-aws-cli#134]
When launching maws from the command line, the role picker is presented twice.

**What happens:**
Execute `$(maws)`
Firefox launches with the role picker on localhost:10800
I select a role
A new tab opens with the role picker on localhost:10801
I select a role again
I'm returned to terminal and able to interact with aws

**What I expect to happen**
After selecting a role the first time, I'm returned to the terminal

**Comment by tristanweir** [comment]
This also happens when trying to launch the web console via `$(maws -w)`

**Comment by april** [comment]
Looks like this is related to YADR + zsh. I'm gonna update the documentation for this.

**Comment by tristanweir** [comment]
Confirmed that a non-[YADR](https://github.com/skwp/dotfiles) zsh launches the web ui only once. So it is definitely isolated to something YADR is doing.
