### ISSUE TITLE
Pip install installs to $HOME/.local/bin by default, which is not on default PATH

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/mozilla-aws-cli#135]
On MacOS Catalina, pip install appears to default install of maws to $HOME/.local/bin and not one of the more common/default $PATH entries.

I have not encountered this when using pip to install other packages. However, it may be that this is correct behavior.

I have updated my PATH to include $HOME/.local/bin

**Comment by gene1wood** [comment]
@tristanweir and was your command `pip install mozilla-aws-cli-mozilla --user --upgrade`? I want to find out if it contained the `--user`

**Comment by tristanweir** [comment]
Correct: `$ pip install mozilla-aws-cli-mozilla --user --upgrade`

**Comment by gene1wood** [comment]
@tristanweir did you get [this warning from pip](https://github.com/pypa/pip/pull/4553/files#diff-79304b3f74b6bf37043da4d96ccd3755R186-R187) when you ran the install saying

> The {} installed in '{}' which is not on PATH. Consider adding {} to PATH or, if you prefer     to suppress this warning, use --no-warn-script-location."

This issue is reported in pypa/pip#3813 and supposedly fixed by warning the user in pypa/pip#4553

**Comment by tristanweir** [comment]
> @tristanweir did you get [this warning from pip](https://github.com/pypa/pip/pull/4553/files#diff-79304b3f74b6bf37043da4d96ccd3755R186-R187) when you ran the install saying
> 
> > The {} installed in '{}' which is not on PATH. Consider adding {} to PATH or, if you prefer     to suppress this warning, use --no-warn-script-location."
> 
> This issue is reported in [pypa/pip#3813](https://github.com/pypa/pip/issues/3813) and supposedly fixed by warning the user in [pypa/pip#4553](https://github.com/pypa/pip/pull/4553)

Yes, I got the warning and subsequently added the appropriate directory to PATH. I just wasn't sure if

1. My setup is different than expected for not having that directory in PATH, or
2. It is a better UX to install to a more commonly found directory in PATH (if such a thing is knowable)

**Comment by gene1wood** [comment]
It looks like this is an issue with `pip`. Our tool doesn't pick the path to install the `entry_point` into and it looks like pypa decided to address this problem by adding that warning. I'll add some language to the mana page to help our users if they encounter this.
