### ISSUE TITLE
Detect if config module and config file assert a conflicting setting

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-aws-cli#137]
If the config module is present, and a config file is present, and they both assert the same key (e.g. `clientid`) and the value of that key differs

Instead of deciding which one we use by precedence (e.g. the config module gets overwritten by the etc file which gets overwritten by the user's config), give the user an error along the lines of "you've got a setting in the config module and in your config file that differ, please either uninstall the module or remove that setting from your config file"

**Comment by april** [comment]
This was fixed in #151.
