### ISSUE TITLE
-o awscli creates a new profile, but has no default region

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-aws-cli#138]
This means that if you just run:
`eval $(maws -o awscli)`

then `aws s3 ls`

you will get an error from aws cli asking you to set a region. I'm not sure what the best solution is here, but it would be nice to have it "work by default"

**Comment by gene1wood** [comment]
Ya, April and I talked about this but settled on requiring the user to assert a region (just as they must if there were using `awscli` or `boto3` without `maws`). We'd have no way of guessing which region the user intended to act on and I'd rather not guess.

This behavior (of requiring the user to assert the region either in their config or environment) is consistent with all other AWS interactions (web, cli and sdk)
