### ISSUE TITLE
Gracefully handle all possible IAM Role max session durations

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-aws-cli#141]
Currently `maws` attempts to provision a 12 hour session, if that fails it tries 1 hour, if that fails it just fails.

We could
* Try 12, then try 1, then try 15 minutes which is the minimum, then fail
* Try 12, then 1 then 15 and when the max is found cache that value so next time we skip right to the session length we need
* Update the group role map builder to determine the max session length for the role and add that to the map. Then when a user picks a role we use the value in our cached local group role map builder

We could also encode this value, if we were confident it was correct, in the [issuer query](https://github.com/mozilla-iam/mozilla-aws-cli/blob/8516cea0e0b938711dbea547d05ea9bf62345dcf/mozilla_aws_cli/login.py#L353) using the [`session_duration` query parameter](https://github.com/mozilla-iam/federated-aws-rp/blob/aa450384a3d848f2c5c98fb8c7bc697653a58e11/functions/federated_aws_rp/app.py#L242-L243)

https://mana.mozilla.org/wiki/display/SECURITY/AWS+Federated+Login+Advanced+Details#AWSFederatedLoginAdvancedDetails-SessionLength

**Comment by april** [comment]
This is really messy, simply because how does the tool if it's been increased at a later time? Does AWS not have a way to query this?
