### ISSUE TITLE
Add a new default role in the cloud formation template

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-iam/mozilla-aws-cli#144]
Currently when setting up an AWS account we create 2 default roles: Admin and "Read".

The read role is inherited from AWS default and gives no access to data, only configuration. For example you cannot read S3 buckets or DynamoDB table contents.

Proposal: Create a third role which gives data access by default, so that the 3 roles look like this:

- admin
- read-configuration
- read-with-data-access

(names could be different of course)

**Comment by gene1wood** [comment]
The AWS managed policies in question here are
* `ReadOnlyAccess` which grants abilities to get s3 files and query dyanmodb
* `ViewOnlyAccess` which grants abilities to describe resources but not read their payload

Currently EIS is using non standard federated roles where the `EISProdRead` role is using `ViewOnlyAccess`.

The roles that we're going to [roll out to everyone](https://github.com/mozilla/security/blob/master/operations/cloudformation-templates/default_oidc_federated_roles.yaml) currently map
* `MAWS-ReadOnly` to `ReadOnlyAccess`
* `MAWS-Admin` to `AdministratorAccess`

@gdestuynder should we add a third role
* `MAWS-ViewOnly` which maps to `ViewOnlyAccess`

Or should we ignore this distinction between view and read and leave the defaults as they are which grant the `MAWS-ReadOnly` role the ability to read s3 payload and dyamodb query?

**Comment by gdestuynder** [comment]
my vote would go for having all 3:
- `ReadOnlyAccess`
- `ViewOnlyAccess`
- `AdministratorAccess`

Note that you'll likely want to have the webui clearly indicate the difference between "view" (no payload access) and "read" (full access)

**Comment by gene1wood** [comment]
This is fixed in mozilla/security#48. The resulting template has been deployed to the prod S3 bucket so it's usable from the quick launch link.
