### ISSUE TITLE
Merge config module and config file if no conflicting settings

### ISSUE THREAD

**Issue by april** [mozilla-iam/mozilla-aws-cli#148]
If the config module and the config file don't have any conflicting settings, they should be merged successfully. This is useful in cases where you might have only `output = shared` in your config file.

**Comment by gene1wood** [comment]
Ya, this must be a bug because [it should do just that as you describe](https://github.com/mozilla-iam/mozilla-aws-cli/blob/ea43d88896b8f0c8ffd89b23ee51c7223fe5a183/mozilla_aws_cli/cli.py#L78-L82)
