### ISSUE TITLE
Web console logout causing CSP error

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-aws-cli#153]
When running `maws -w` the console shows the error

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://aws.amazon.com/ (“img-src”).
```

After selecting a role. This may be related to the logout image with AWS

**Comment by april** [comment]
It is related to the logout function; the logout URL redirects a regular HTML page. There's not a good reason to load all of that page in the background (and it may mess up the image thing), so I would rather leave that CSP in place even though it generates an error.
