### ISSUE TITLE
Windows path issues

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-aws-cli#161]
Upon installing on Windows 10 with a command like `pip install --user mozilla-aws-cli-mozilla` which in turn installs `mozilla-aws-cli` I see two problems

* The `maws.exe` binary isn't in the path
* When running `maws.exe` it complains that the `pwd` module is missing.

**Comment by april** [comment]
Fixed in 49c7d17aaa95724398ae8149f3b9655cab6dde73.
