### ISSUE TITLE
Add option to just output aws console URL instead of redirecting

### ISSUE THREAD

**Issue by limed** [mozilla-iam/mozilla-aws-cli#205]
Sometimes we have to open multiple AWS consoles (we do this using container tabs) so on top of the `maws -w` command can we get an additional flag like `--url` for example that will print out the AWS console URL for federated users once we have done the SSO dance.

See: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-custom-url.html

**Comment by gene1wood** [comment]
I was looking at #213 but haven't found a perfect solution yet.
