### ISSUE TITLE
Maws extending shell prompt indefinitely

### ISSUE THREAD

**Issue by arcrose** [mozilla-iam/mozilla-aws-cli#211]
If you run maws multiple times to switch between a couple of different roles, your prompt will be extended with the name of each role you assume, one after the other.  Upon each execution of maws, it would be nice to clear the prompt.

**Comment by april** [comment]
This was actually fixed in #207, but I dunno if @gene1wood has pushed it out at all.

**Comment by gene1wood** [comment]
This has been deployed in [v1.2.0](https://pypi.org/project/mozilla-aws-cli/1.2.0/)
