### ISSUE TITLE
Error : KeyError: 'WERKZEUG_SERVER_FD'

### ISSUE THREAD

**Issue by gene1wood** [mozilla-iam/mozilla-aws-cli#243]
This line in `maws`

https://github.com/mozilla-iam/mozilla-aws-cli/blob/6de1d9223f14d2ad5cae85856e2c7036ab8237eb/mozilla_aws_cli/listener.py#L237

appears to be triggering this issue https://github.com/pallets/werkzeug/issues/2368

We're setting `os.environ["WERKZEUG_RUN_MAIN"] = "true"` in order to suppress the printing to the console of Flask information (as mentioned in https://github.com/cs01/gdbgui/issues/425#issuecomment-1086867667 )

The workaround for the moment appears to be downgrading werkzeug `pip install 'Werkzeug<2.1.0'`

**Comment by hwine** [comment]
Should we also be pinning all the requirements?  Especially if maws is installable via `pipx`, pinning would be a good thing.

**Comment by gene1wood** [comment]
> Should we also be pinning all the requirements? Especially if maws is installable via pipx, pinning would be a good thing.

Ya, that would probably be good. I'd say open an issue or PR that change.

This fix is deployed and available in `mozilla-aws-cli==1.2.5`
