### ISSUE TITLE
Use reasonable default settings when there's no configuration file

### ISSUE THREAD

**Issue by april** [mozilla-iam/mozilla-aws-cli#67]
When there isn't a configuration file, the client should probably default to the Mozilla Prod settings. This is especially so since it's likely it will be installed via pip, and it would be nice to work out of the box.

**Comment by gene1wood** [comment]
This has been accomplished with the [`mozilla-aws-cli-mozilla`](https://test.pypi.org/project/mozilla-aws-cli-mozilla/) package and the new [enterprise organization configuration model](https://github.com/mozilla-iam/mozilla-aws-cli#creating-enterprise--organization-configuration)
